
var blosc_codec = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(moduleArg = {}) {

var f=moduleArg,aa,p;f.ready=new Promise((a,b)=>{aa=a;p=b});var ba=Object.assign({},f),ca="./this.program",da=f.print||console.log.bind(console),r=f.printErr||console.error.bind(console);Object.assign(f,ba);ba=null;f.thisProgram&&(ca=f.thisProgram);var t;f.wasmBinary&&(t=f.wasmBinary);"object"!=typeof WebAssembly&&w("no native wasm support detected");var x,ea=!1,z,A,B,C,D,E,fa,ha;
function ia(){var a=x.buffer;f.HEAP8=z=new Int8Array(a);f.HEAP16=B=new Int16Array(a);f.HEAPU8=A=new Uint8Array(a);f.HEAPU16=C=new Uint16Array(a);f.HEAP32=D=new Int32Array(a);f.HEAPU32=E=new Uint32Array(a);f.HEAPF32=fa=new Float32Array(a);f.HEAPF64=ha=new Float64Array(a)}var ja=[],ka=[],la=[];function ma(){var a=f.preRun.shift();ja.unshift(a)}var F=0,G=null,H=null;
function w(a){f.onAbort?.(a);a="Aborted("+a+")";r(a);ea=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");p(a);throw a;}var na=a=>a.startsWith("data:application/octet-stream;base64,"),oa=a=>a.startsWith("file://"),I;I="blosc_codec.wasm";if(!na(I)){var pa=I;I=f.locateFile?f.locateFile(pa,""):""+pa}function qa(a){return Promise.resolve().then(()=>{if(a==I&&t)var b=new Uint8Array(t);else throw"both async and sync fetching of the wasm failed";return b})}
function ra(a,b,c){return qa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{r(`failed to asynchronously prepare wasm: ${d}`);w(d)})}function sa(a,b){var c=I;return t||"function"!=typeof WebAssembly.instantiateStreaming||na(c)||oa(c)||"function"!=typeof fetch?ra(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){r(`wasm streaming compile failed: ${e}`);r("falling back to ArrayBuffer instantiation");return ra(c,a,b)}))}
var J=a=>{for(;0<a.length;)a.shift()(f)};function ta(a){this.H=a-24;this.N=function(b){E[this.H+4>>2]=b};this.M=function(b){E[this.H+8>>2]=b};this.I=function(b,c){this.J();this.N(b);this.M(c)};this.J=function(){E[this.H+16>>2]=0}}
var ua=0,va=0,wa,K=a=>{for(var b="";A[a];)b+=wa[A[a++]];return b},L={},M={},N={},O,P,xa=(a,b)=>{function c(h){h=b(h);if(h.length!==d.length)throw new P("Mismatched type converter count");for(var k=0;k<d.length;++k)Q(d[k],h[k])}var d=[];d.forEach(function(h){N[h]=a});var e=Array(a.length),g=[],l=0;a.forEach((h,k)=>{M.hasOwnProperty(h)?e[k]=M[h]:(g.push(h),L.hasOwnProperty(h)||(L[h]=[]),L[h].push(()=>{e[k]=M[h];++l;l===g.length&&c(e)}))});0===g.length&&c(e)};
function ya(a,b,c={}){var d=b.name;if(!a)throw new O(`type "${d}" must have a positive integer typeid pointer`);if(M.hasOwnProperty(a)){if(c.P)return;throw new O(`Cannot register type '${d}' twice`);}M[a]=b;delete N[a];L.hasOwnProperty(a)&&(b=L[a],delete L[a],b.forEach(e=>e()))}function Q(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");ya(a,b,c)}function za(){this.F=[void 0];this.K=[]}
var R=new za,Aa=a=>{a>=R.H&&0===--R.get(a).L&&R.J(a)},Ba=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return R.I({L:1,value:a})}};function Ca(a){return this.fromWireType(D[a>>2])}var Da=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(fa[c>>2])};case 8:return function(c){return this.fromWireType(ha[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ea=(a,b)=>Object.defineProperty(b,"name",{value:a});
function Fa(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].G)return!0;return!1}
function Ga(a,b,c,d){var e=b.length;if(2>e)throw new O("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&!1,l=Fa(b),h="void"!==b[0].name,k=e-2,m=Array(k),n=[],q=[];return Ea(a,function(){if(arguments.length!==k)throw new O(`function ${a} called with ${arguments.length} arguments, expected ${k}`);q.length=0;n.length=g?2:1;n[0]=d;if(g){var u=b[1].toWireType(q,this);n[1]=u}for(var v=0;v<k;++v)m[v]=b[v+2].toWireType(q,arguments[v]),n.push(m[v]);v=c.apply(null,
n);if(l)for(;q.length;)u=q.pop(),q.pop()(u);else for(var y=g?1:2;y<b.length;y++){var Qa=1===y?u:m[y-2];null!==b[y].G&&b[y].G(Qa)}u=h?b[0].fromWireType(v):void 0;return u})}
var Ha=(a,b)=>{if(void 0===f[a].C){var c=f[a];f[a]=function(){if(!f[a].C.hasOwnProperty(arguments.length))throw new O(`Function '${b}' called with an invalid number of arguments (${arguments.length}) - expects one of (${f[a].C})!`);return f[a].C[arguments.length].apply(this,arguments)};f[a].C=[];f[a].C[c.O]=c}},Ia=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].C&&void 0!==f[a].C[c])throw new O(`Cannot register public name '${a}' twice`);Ha(a,a);if(f.hasOwnProperty(c))throw new O(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
f[a].C[c]=b}else f[a]=b,void 0!==c&&(f[a].S=c)},Ja=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(E[b+4*d>>2]);return c},S,Ka=(a,b)=>{var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=f["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=S.get(b).apply(null,c);return d}},La=(a,b)=>{a=K(a);var c=a.includes("j")?Ka(a,b):S.get(b);if("function"!=typeof c)throw new O(`unknown function pointer with signature ${a}: ${b}`);return c},Ma,Oa=a=>{a=
Na(a);var b=K(a);T(a);return b},Pa=(a,b)=>{function c(g){e[g]||M[g]||(N[g]?N[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new Ma(`${a}: `+d.map(Oa).join([", "]));},Ra=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Sa=(a,b,c)=>{switch(b){case 1:return c?d=>z[d>>0]:d=>A[d>>0];case 2:return c?d=>B[d>>1]:d=>C[d>>1];case 4:return c?d=>D[d>>2]:d=>E[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}};
function Ta(a){return this.fromWireType(E[a>>2])}
for(var Ua="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,Va=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ua)return Ua.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|l:(e&7)<<18|g<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Wa="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Xa=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&C[c];)++c;c<<=1;if(32<c-a&&Wa)return Wa.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=B[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Ya=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)B[b>>1]=a.charCodeAt(e),b+=2;B[b>>1]=0;return b-d},Za=a=>2*a.length,$a=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=D[a+4*
c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},ab=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var l=a.charCodeAt(++e);g=65536+((g&1023)<<10)|l&1023}D[b>>2]=g;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d},bb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},U={},cb=()=>{if(!V){var a={USER:"web_user",
LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in U)void 0===U[b]?delete a[b]:a[b]=U[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);V=c}return V},V,db=[null,[],[]],eb=Array(256),W=0;256>W;++W)eb[W]=String.fromCharCode(W);wa=eb;O=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
P=f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};Object.assign(za.prototype,{get(a){return this.F[a]},has(a){return void 0!==this.F[a]},I(a){var b=this.K.pop()||this.F.length;this.F[b]=a;return b},J(a){this.F[a]=void 0;this.K.push(a)}});R.F.push({value:void 0},{value:null},{value:!0},{value:!1});R.H=R.F.length;f.count_emval_handles=()=>{for(var a=0,b=R.H;b<R.F.length;++b)void 0!==R.F[b]&&++a;return a};
Ma=f.UnboundTypeError=((a,b)=>{var c=Ea(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var fb={p:(a,b,c)=>{(new ta(a)).I(b,c);ua=a;va++;throw ua;},o:()=>{},l:(a,b,c,d)=>{b=K(b);Q(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,g){return g?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(A[e])},G:null})},k:(a,b)=>{b=K(b);Q(a,{name:b,fromWireType:c=>{if(!c)throw new O("Cannot use deleted val. handle = "+c);var d=R.get(c).value;Aa(c);return d},toWireType:(c,d)=>Ba(d),argPackAdvance:8,readValueFromPointer:Ca,G:null})},i:(a,b,c)=>{b=K(b);
Q(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:Da(b,c),G:null})},d:(a,b,c,d,e,g)=>{var l=Ja(b,c);a=K(a);a=Ra(a);e=La(d,e);Ia(a,function(){Pa(`Cannot call ${a} due to unbound types`,l)},b-1);xa(l,function(h){var k=a;h=Ga(a,[h[0],null].concat(h.slice(1)),e,g);var m=b-1;if(!f.hasOwnProperty(k))throw new P("Replacing nonexistant public symbol");void 0!==f[k].C&&void 0!==m?f[k].C[m]=h:(f[k]=h,f[k].O=m);return[]})},b:(a,b,c,d,e)=>{b=K(b);-1===e&&(e=4294967295);e=
h=>h;if(0===d){var g=32-8*c;e=h=>h<<g>>>g}var l=b.includes("unsigned")?function(h,k){return k>>>0}:function(h,k){return k};Q(a,{name:b,fromWireType:e,toWireType:l,argPackAdvance:8,readValueFromPointer:Sa(b,c,0!==d),G:null})},a:(a,b,c)=>{function d(g){return new e(z.buffer,E[g+4>>2],E[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=K(c);Q(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{P:!0})},e:(a,b)=>{b=K(b);var c=
"std::string"===b;Q(a,{name:b,fromWireType:function(d){var e=E[d>>2],g=d+4;if(c)for(var l=g,h=0;h<=e;++h){var k=g+h;if(h==e||0==A[k]){l=l?Va(A,l,k-l):"";if(void 0===m)var m=l;else m+=String.fromCharCode(0),m+=l;l=k+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(A[g+h]);m=m.join("")}T(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g,l="string"==typeof e;if(!(l||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new O("Cannot pass non-string to std::string");
var h;if(c&&l)for(g=h=0;g<e.length;++g){var k=e.charCodeAt(g);127>=k?h++:2047>=k?h+=2:55296<=k&&57343>=k?(h+=4,++g):h+=3}else h=e.length;g=h;h=X(4+g+1);k=h+4;E[h>>2]=g;if(c&&l){if(l=k,k=g+1,g=A,0<k){k=l+k-1;for(var m=0;m<e.length;++m){var n=e.charCodeAt(m);if(55296<=n&&57343>=n){var q=e.charCodeAt(++m);n=65536+((n&1023)<<10)|q&1023}if(127>=n){if(l>=k)break;g[l++]=n}else{if(2047>=n){if(l+1>=k)break;g[l++]=192|n>>6}else{if(65535>=n){if(l+2>=k)break;g[l++]=224|n>>12}else{if(l+3>=k)break;g[l++]=240|n>>
18;g[l++]=128|n>>12&63}g[l++]=128|n>>6&63}g[l++]=128|n&63}}g[l]=0}}else if(l)for(l=0;l<g;++l){m=e.charCodeAt(l);if(255<m)throw T(k),new O("String has UTF-16 code units that do not fit in 8 bits");A[k+l]=m}else for(l=0;l<g;++l)A[k+l]=e[l];null!==d&&d.push(T,h);return h},argPackAdvance:8,readValueFromPointer:Ta,G(d){T(d)}})},c:(a,b,c)=>{c=K(c);if(2===b){var d=Xa;var e=Ya;var g=Za;var l=()=>C;var h=1}else 4===b&&(d=$a,e=ab,g=bb,l=()=>E,h=2);Q(a,{name:c,fromWireType:k=>{for(var m=E[k>>2],n=l(),q,u=k+
4,v=0;v<=m;++v){var y=k+4+v*b;if(v==m||0==n[y>>h])u=d(u,y-u),void 0===q?q=u:(q+=String.fromCharCode(0),q+=u),u=y+b}T(k);return q},toWireType:(k,m)=>{if("string"!=typeof m)throw new O(`Cannot pass non-string to C++ string type ${c}`);var n=g(m),q=X(4+n+b);E[q>>2]=n>>h;e(m,q+4,n+b);null!==k&&k.push(T,q);return q},argPackAdvance:8,readValueFromPointer:Ca,G(k){T(k)}})},m:(a,b)=>{b=K(b);Q(a,{R:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},g:Aa,j:a=>{4<a&&(R.get(a).L+=1)},f:(a,b)=>
{var c=M[a];if(void 0===c)throw a="_emval_take_value has unknown type "+Oa(a),new O(a);a=c;a=a.readValueFromPointer(b);return Ba(a)},h:()=>{w("")},v:(a,b,c)=>A.copyWithin(a,b,b+c),q:a=>{var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-x.buffer.byteLength+65535)/65536;try{x.grow(e);ia();var g=1;break a}catch(l){}g=void 0}if(g)return!0}return!1},t:(a,b)=>
{var c=0;cb().forEach((d,e)=>{var g=b+c;e=E[a+4*e>>2]=g;for(g=0;g<d.length;++g)z[e++>>0]=d.charCodeAt(g);z[e>>0]=0;c+=d.length+1});return 0},u:(a,b)=>{var c=cb();E[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);E[b>>2]=d;return 0},s:()=>52,n:function(){return 70},r:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var l=E[b>>2],h=E[b+4>>2];b+=8;for(var k=0;k<h;k++){var m=A[l+k],n=db[a];0===m||10===m?((1===a?da:r)(Va(n,0)),n.length=0):n.push(m)}e+=h}E[d>>2]=e;return 0}},Y=function(){function a(c){Y=c.exports;
x=Y.w;ia();S=Y.A;ka.unshift(Y.x);F--;f.monitorRunDependencies?.(F);0==F&&(null!==G&&(clearInterval(G),G=null),H&&(c=H,H=null,c()));return Y}var b={a:fb};F++;f.monitorRunDependencies?.(F);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){r(`Module.instantiateWasm callback failed with error: ${c}`),p(c)}sa(b,function(c){a(c.instance)}).catch(p);return{}}(),X=a=>(X=Y.y)(a),T=a=>(T=Y.z)(a),Na=a=>(Na=Y.B)(a);f.dynCall_jiji=(a,b,c,d,e)=>(f.dynCall_jiji=Y.D)(a,b,c,d,e);var Z;
H=function gb(){Z||hb();Z||(H=gb)};
function hb(){function a(){if(!Z&&(Z=!0,f.calledRun=!0,!ea)){J(ka);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();la.unshift(b)}J(la)}}if(!(0<F)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ma();J(ja);0<F||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();hb();


  return moduleArg.ready
}
);
})();
;
export default blosc_codec;