
var lz4_codec = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(moduleArg = {}) {

var f=moduleArg,t,u;f.ready=new Promise((a,b)=>{t=a;u=b});var aa=Object.assign({},f),v=f.printErr||console.error.bind(console);Object.assign(f,aa);aa=null;var x;f.wasmBinary&&(x=f.wasmBinary);"object"!=typeof WebAssembly&&y("no native wasm support detected");var A,ba=!1,B,C,D,E,F,G,ca,da;
function ea(){var a=A.buffer;f.HEAP8=B=new Int8Array(a);f.HEAP16=D=new Int16Array(a);f.HEAPU8=C=new Uint8Array(a);f.HEAPU16=E=new Uint16Array(a);f.HEAP32=F=new Int32Array(a);f.HEAPU32=G=new Uint32Array(a);f.HEAPF32=ca=new Float32Array(a);f.HEAPF64=da=new Float64Array(a)}var fa=[],ha=[],ia=[];function ja(){var a=f.preRun.shift();fa.unshift(a)}var H=0,I=null,J=null;
function y(a){f.onAbort?.(a);a="Aborted("+a+")";v(a);ba=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");u(a);throw a;}var ka=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),K;K="lz4_codec.wasm";if(!ka(K)){var ma=K;K=f.locateFile?f.locateFile(ma,""):""+ma}function na(a){return Promise.resolve().then(()=>{if(a==K&&x)var b=new Uint8Array(x);else throw"both async and sync fetching of the wasm failed";return b})}
function oa(a,b,c){return na(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{v(`failed to asynchronously prepare wasm: ${d}`);y(d)})}function pa(a,b){var c=K;return x||"function"!=typeof WebAssembly.instantiateStreaming||ka(c)||la(c)||"function"!=typeof fetch?oa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){v(`wasm streaming compile failed: ${e}`);v("falling back to ArrayBuffer instantiation");return oa(c,a,b)}))}
var L=a=>{for(;0<a.length;)a.shift()(f)};function qa(a){this.D=a-24;this.K=function(b){G[this.D+4>>2]=b};this.J=function(b){G[this.D+8>>2]=b};this.F=function(b,c){this.G();this.K(b);this.J(c)};this.G=function(){G[this.D+16>>2]=0}}
var ra=0,sa=0,ta,M=a=>{for(var b="";C[a];)b+=ta[C[a++]];return b},N={},O={},P={},Q,R,ua=(a,b)=>{function c(k){k=b(k);if(k.length!==d.length)throw new R("Mismatched type converter count");for(var l=0;l<d.length;++l)S(d[l],k[l])}var d=[];d.forEach(function(k){P[k]=a});var e=Array(a.length),g=[],h=0;a.forEach((k,l)=>{O.hasOwnProperty(k)?e[l]=O[k]:(g.push(k),N.hasOwnProperty(k)||(N[k]=[]),N[k].push(()=>{e[l]=O[k];++h;h===g.length&&c(e)}))});0===g.length&&c(e)};
function va(a,b,c={}){var d=b.name;if(!a)throw new Q(`type "${d}" must have a positive integer typeid pointer`);if(O.hasOwnProperty(a)){if(c.M)return;throw new Q(`Cannot register type '${d}' twice`);}O[a]=b;delete P[a];N.hasOwnProperty(a)&&(b=N[a],delete N[a],b.forEach(e=>e()))}function S(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");va(a,b,c)}function wa(){this.B=[void 0];this.H=[]}
var T=new wa,xa=a=>{a>=T.D&&0===--T.get(a).I&&T.G(a)},ya=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return T.F({I:1,value:a})}};function za(a){return this.fromWireType(F[a>>2])}var Aa=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ca[c>>2])};case 8:return function(c){return this.fromWireType(da[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ba=(a,b)=>Object.defineProperty(b,"name",{value:a});
function Ca(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].C)return!0;return!1}
function Da(a,b,c,d){var e=b.length;if(2>e)throw new Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&!1,h=Ca(b),k="void"!==b[0].name,l=e-2,m=Array(l),n=[],p=[];return Ba(a,function(){if(arguments.length!==l)throw new Q(`function ${a} called with ${arguments.length} arguments, expected ${l}`);p.length=0;n.length=g?2:1;n[0]=d;if(g){var q=b[1].toWireType(p,this);n[1]=q}for(var r=0;r<l;++r)m[r]=b[r+2].toWireType(p,arguments[r]),n.push(m[r]);r=c.apply(null,
n);if(h)for(;p.length;)q=p.pop(),p.pop()(q);else for(var w=g?1:2;w<b.length;w++){var z=1===w?q:m[w-2];null!==b[w].C&&b[w].C(z)}q=k?b[0].fromWireType(r):void 0;return q})}
var Ea=(a,b)=>{if(void 0===f[a].A){var c=f[a];f[a]=function(){if(!f[a].A.hasOwnProperty(arguments.length))throw new Q(`Function '${b}' called with an invalid number of arguments (${arguments.length}) - expects one of (${f[a].A})!`);return f[a].A[arguments.length].apply(this,arguments)};f[a].A=[];f[a].A[c.L]=c}},Fa=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].A&&void 0!==f[a].A[c])throw new Q(`Cannot register public name '${a}' twice`);Ea(a,a);if(f.hasOwnProperty(c))throw new Q(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
f[a].A[c]=b}else f[a]=b,void 0!==c&&(f[a].O=c)},Ga=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(G[b+4*d>>2]);return c},U,Ha=(a,b)=>{var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=f["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=U.get(b).apply(null,c);return d}},Ia=(a,b)=>{a=M(a);var c=a.includes("j")?Ha(a,b):U.get(b);if("function"!=typeof c)throw new Q(`unknown function pointer with signature ${a}: ${b}`);return c},Ja,La=a=>{a=
Ka(a);var b=M(a);V(a);return b},Ma=(a,b)=>{function c(g){e[g]||O[g]||(P[g]?P[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new Ja(`${a}: `+d.map(La).join([", "]));},Na=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Oa=(a,b,c)=>{switch(b){case 1:return c?d=>B[d>>0]:d=>C[d>>0];case 2:return c?d=>D[d>>1]:d=>E[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}};
function Pa(a){return this.fromWireType(G[a>>2])}
for(var Qa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,Ra="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Sa=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&E[c];)++c;c<<=1;if(32<c-a&&Ra)return Ra.decode(C.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=D[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Ta=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-
d},Ua=a=>2*a.length,Va=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=F[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Wa=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);g=65536+((g&1023)<<10)|h&1023}F[b>>2]=g;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d},Xa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);
55296<=d&&57343>=d&&++c;b+=4}return b},Ya=Array(256),W=0;256>W;++W)Ya[W]=String.fromCharCode(W);ta=Ya;Q=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};R=f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};Object.assign(wa.prototype,{get(a){return this.B[a]},has(a){return void 0!==this.B[a]},F(a){var b=this.H.pop()||this.B.length;this.B[b]=a;return b},G(a){this.B[a]=void 0;this.H.push(a)}});
T.B.push({value:void 0},{value:null},{value:!0},{value:!1});T.D=T.B.length;f.count_emval_handles=()=>{for(var a=0,b=T.D;b<T.B.length;++b)void 0!==T.B[b]&&++a;return a};
Ja=f.UnboundTypeError=((a,b)=>{var c=Ba(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var Za={n:(a,b,c)=>{(new qa(a)).F(b,c);ra=a;sa++;throw ra;},o:()=>{},l:(a,b,c,d)=>{b=M(b);S(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,g){return g?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(C[e])},C:null})},k:(a,b)=>{b=M(b);S(a,{name:b,fromWireType:c=>{if(!c)throw new Q("Cannot use deleted val. handle = "+c);var d=T.get(c).value;xa(c);return d},toWireType:(c,d)=>ya(d),argPackAdvance:8,readValueFromPointer:za,C:null})},i:(a,b,c)=>{b=M(b);
S(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:Aa(b,c),C:null})},d:(a,b,c,d,e,g)=>{var h=Ga(b,c);a=M(a);a=Na(a);e=Ia(d,e);Fa(a,function(){Ma(`Cannot call ${a} due to unbound types`,h)},b-1);ua(h,function(k){var l=a;k=Da(a,[k[0],null].concat(k.slice(1)),e,g);var m=b-1;if(!f.hasOwnProperty(l))throw new R("Replacing nonexistant public symbol");void 0!==f[l].A&&void 0!==m?f[l].A[m]=k:(f[l]=k,f[l].L=m);return[]})},b:(a,b,c,d,e)=>{b=M(b);-1===e&&(e=4294967295);e=
k=>k;if(0===d){var g=32-8*c;e=k=>k<<g>>>g}var h=b.includes("unsigned")?function(k,l){return l>>>0}:function(k,l){return l};S(a,{name:b,fromWireType:e,toWireType:h,argPackAdvance:8,readValueFromPointer:Oa(b,c,0!==d),C:null})},a:(a,b,c)=>{function d(g){return new e(B.buffer,G[g+4>>2],G[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=M(c);S(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{M:!0})},e:(a,b)=>{b=M(b);var c=
"std::string"===b;S(a,{name:b,fromWireType:function(d){var e=G[d>>2],g=d+4;if(c)for(var h=g,k=0;k<=e;++k){var l=g+k;if(k==e||0==C[l]){if(h){var m=h;var n=C,p=m+(l-h);for(h=m;n[h]&&!(h>=p);)++h;if(16<h-m&&n.buffer&&Qa)m=Qa.decode(n.subarray(m,h));else{for(p="";m<h;){var q=n[m++];if(q&128){var r=n[m++]&63;if(192==(q&224))p+=String.fromCharCode((q&31)<<6|r);else{var w=n[m++]&63;q=224==(q&240)?(q&15)<<12|r<<6|w:(q&7)<<18|r<<12|w<<6|n[m++]&63;65536>q?p+=String.fromCharCode(q):(q-=65536,p+=String.fromCharCode(55296|
q>>10,56320|q&1023))}}else p+=String.fromCharCode(q)}m=p}}else m="";if(void 0===z)var z=m;else z+=String.fromCharCode(0),z+=m;h=l+1}}else{z=Array(e);for(k=0;k<e;++k)z[k]=String.fromCharCode(C[g+k]);z=z.join("")}V(d);return z},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g,h="string"==typeof e;if(!(h||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new Q("Cannot pass non-string to std::string");var k;if(c&&h)for(g=k=0;g<e.length;++g){var l=
e.charCodeAt(g);127>=l?k++:2047>=l?k+=2:55296<=l&&57343>=l?(k+=4,++g):k+=3}else k=e.length;g=k;k=X(4+g+1);l=k+4;G[k>>2]=g;if(c&&h){if(h=l,l=g+1,g=C,0<l){l=h+l-1;for(var m=0;m<e.length;++m){var n=e.charCodeAt(m);if(55296<=n&&57343>=n){var p=e.charCodeAt(++m);n=65536+((n&1023)<<10)|p&1023}if(127>=n){if(h>=l)break;g[h++]=n}else{if(2047>=n){if(h+1>=l)break;g[h++]=192|n>>6}else{if(65535>=n){if(h+2>=l)break;g[h++]=224|n>>12}else{if(h+3>=l)break;g[h++]=240|n>>18;g[h++]=128|n>>12&63}g[h++]=128|n>>6&63}g[h++]=
128|n&63}}g[h]=0}}else if(h)for(h=0;h<g;++h){m=e.charCodeAt(h);if(255<m)throw V(l),new Q("String has UTF-16 code units that do not fit in 8 bits");C[l+h]=m}else for(h=0;h<g;++h)C[l+h]=e[h];null!==d&&d.push(V,k);return k},argPackAdvance:8,readValueFromPointer:Pa,C(d){V(d)}})},c:(a,b,c)=>{c=M(c);if(2===b){var d=Sa;var e=Ta;var g=Ua;var h=()=>E;var k=1}else 4===b&&(d=Va,e=Wa,g=Xa,h=()=>G,k=2);S(a,{name:c,fromWireType:l=>{for(var m=G[l>>2],n=h(),p,q=l+4,r=0;r<=m;++r){var w=l+4+r*b;if(r==m||0==n[w>>k])q=
d(q,w-q),void 0===p?p=q:(p+=String.fromCharCode(0),p+=q),q=w+b}V(l);return p},toWireType:(l,m)=>{if("string"!=typeof m)throw new Q(`Cannot pass non-string to C++ string type ${c}`);var n=g(m),p=X(4+n+b);G[p>>2]=n>>k;e(m,p+4,n+b);null!==l&&l.push(V,p);return p},argPackAdvance:8,readValueFromPointer:za,C(l){V(l)}})},m:(a,b)=>{b=M(b);S(a,{N:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},g:xa,j:a=>{4<a&&(T.get(a).I+=1)},f:(a,b)=>{var c=O[a];if(void 0===c)throw a="_emval_take_value has unknown type "+
La(a),new Q(a);a=c;a=a.readValueFromPointer(b);return ya(a)},h:()=>{y("")},q:(a,b,c)=>C.copyWithin(a,b,b+c),p:a=>{var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-A.buffer.byteLength+65535)/65536;try{A.grow(e);ea();var g=1;break a}catch(h){}g=void 0}if(g)return!0}return!1}},Y=function(){function a(c){Y=c.exports;A=Y.r;ea();U=Y.w;ha.unshift(Y.s);H--;f.monitorRunDependencies?.(H);
0==H&&(null!==I&&(clearInterval(I),I=null),J&&(c=J,J=null,c()));return Y}var b={a:Za};H++;f.monitorRunDependencies?.(H);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){v(`Module.instantiateWasm callback failed with error: ${c}`),u(c)}pa(b,function(c){a(c.instance)}).catch(u);return{}}(),X=a=>(X=Y.t)(a),V=a=>(V=Y.u)(a),Ka=a=>(Ka=Y.v)(a),Z;J=function $a(){Z||ab();Z||(J=$a)};
function ab(){function a(){if(!Z&&(Z=!0,f.calledRun=!0,!ba)){L(ha);t(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();ia.unshift(b)}L(ia)}}if(!(0<H)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ja();L(fa);0<H||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();ab();


  return moduleArg.ready
}
);
})();
;
export default lz4_codec;